/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#730013',
        'primary-container': '#991322',
        'on-primary': '#ffffff',
        'on-primary-container': '#ffa6a3',
        'on-primary-fixed': '#410006',
        'on-primary-fixed-variant': '#900a1d',
        'primary-fixed': '#ffdad8',
        'primary-fixed-dim': '#ffb3b0',
        'inverse-primary': '#ffb3b0',
        secondary: '#a9343b',
        'secondary-container': '#fd7274',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#6f0416',
        'on-secondary-fixed': '#410008',
        'on-secondary-fixed-variant': '#891b25',
        'secondary-fixed': '#ffdad8',
        'secondary-fixed-dim': '#ffb3b1',
        tertiary: '#363636',
        'tertiary-container': '#4d4d4d',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#c0bebd',
        'on-tertiary-fixed': '#1b1c1c',
        'on-tertiary-fixed-variant': '#474746',
        'tertiary-fixed': '#e4e2e1',
        'tertiary-fixed-dim': '#c8c6c5',
        surface: '#f9f9f9',
        'surface-dim': '#dadada',
        'surface-bright': '#f9f9f9',
        'surface-variant': '#e2e2e2',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f3',
        'surface-container': '#eeeeee',
        'surface-container-high': '#e8e8e8',
        'surface-container-highest': '#e2e2e2',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#594140',
        'inverse-surface': '#2f3131',
        'inverse-on-surface': '#f1f1f1',
        'surface-tint': '#b22831',
        outline: '#8d706f',
        'outline-variant': '#e1bebd',
        background: '#f9f9f9',
        'on-background': '#1a1c1c',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
      spacing: {
        gutter: '24px',
        'stack-lg': '48px',
        'margin-mobile': '16px',
        unit: '8px',
        'stack-sm': '12px',
        'stack-md': '24px',
        'container-max': '1200px',
      },
      fontFamily: {
        'label-caps': ['"Public Sans"', 'sans-serif'],
        'headline-lg': ['"Public Sans"', 'sans-serif'],
        'headline-md': ['"Public Sans"', 'sans-serif'],
        'body-md': ['Lexend', 'sans-serif'],
        'body-lg': ['Lexend', 'sans-serif'],
        sans: ['Lexend', 'sans-serif'],
        display: ['"Public Sans"', 'sans-serif'],
      },
      fontSize: {
        'label-caps': ['14px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg': ['36px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['28px', { lineHeight: '1.3', fontWeight: '600' }],
      },
      maxWidth: {
        container: '1200px',
      },
    },
  },
  plugins: [],
};
